### ISSUE TITLE
Optimize images

### ISSUE THREAD

**Issue by batudal** [batudal/decoded-app#9]
- Use vite images to optimize
- Create versions in figma
- Convert to webp
- Serve on CDN

**Comment by batudal** [comment]
Notion entries should take this optimization into account and use webp for blog posts

**Comment by silvijasaule** [comment]
@takez0o I wanted to check how performance changes after changing the main picture from png to webp. It didn't change much, so I compressed webp file. Then the performance changed significantly. 

So now the first picture in the reentrancy attack blog page is a compressed webp file.

**Comment by batudal** [comment]
That's great. I usually use 90% compression ratio with webp conversion. 

Changed second image as well.

**Comment by batudal** [comment]
Oops. I forgot about landing page images completely. I'll make sure to webp them all and update soon.
